# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 169c756d20df7092338776472bfa374796bd92a47723c9a44a43c3b49996c712fec9b0fc5703071dbb492c0a90c6614909f50ba259dd06e21d3f20b0ab6cf03e

test:
  secret_key_base: a026fb92da23ff813d8a1d418f20549788494d5641d0be66db799a8c678f4bd34abcd7332c7dede435f400ee9232337273e235f9db3cbe73cf7d5185d01f5604

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
